export default {
  actions: {
    INSERT_CATEGORY_SUCCESS: 'INSERT_CATEGORY_SUCCESS',
    UPDATE_CATEGORY_SUCCESS: 'UPDATE_CATEGORY_SUCCESS',
    DESTROY_CATEGORY_SUCCESS: 'DESTROY_CATEGORY_SUCCESS',
    LOAD_CATEGORIES_SUCCESS: 'LOAD_CATEGORIES_SUCCESS',
    INSERT_CUSTOMER_SUCCESS: 'INSERT_CUSTOMER_SUCCESS',
    UPDATE_CUSTOMER_SUCCESS: 'UPDATE_CUSTOMER_SUCCESS',
    DESTROY_CUSTOMER_SUCCESS: 'DESTROY_CUSTOMER_SUCCESS',
    LOAD_CUSTOMERS_SUCCESS: 'LOAD_CUSTOMERS_SUCCESS',
    BEGIN_ASYNC_INVOCATION: 'BEGIN_ASYNC_INVOCATION',
    END_ASYNC_INVOCATION: 'END_ASYNC_INVOCATION'
  }
};