export default {
  actions: {
    INSERT_CUSTOMER_SUCCESS: 'INSERT_CUSTOMER_SUCCESS',
    UPDATE_CUSTOMER_SUCCESS: 'UPDATE_CUSTOMER_SUCCESS',
    LOAD_CUSTOMERS_SUCCESS: 'LOAD_CUSTOMERS_SUCCESS',
    BEGIN_ASYNC_INVOCATION: 'BEGIN_ASYNC_INVOCATION'
  }
};